# config/packages/staging/framework.yaml
framework:
    router:
        strict_requirements: true
    profiler:
        collect: true
    cache:
        app: cache.adapter.filesystem

# config/packages/staging/monolog.yaml
monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/staging.log"
            level: debug
            channels: ["!event"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]

# config/packages/prod/framework.yaml
framework:
    router:
        strict_requirements: null
    profiler:
        collect: false
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'

# config/packages/prod/monolog.yaml
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50
        nested:
            type: stream
            path: "%kernel.logs_dir%/prod.log"
            level: debug